Ready for release

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # $OpenLDAP$
-# from OpenLDAP 
+# from OpenLDAP: pkg/ldap/configure.in,v 1.408.2.30 2003/02/10 19:24:24 kurt Exp  
 
 # Copyright 1998-2003 The OpenLDAP Foundation.  All Rights Reserved.
 # 
@@ -30,9 +30,9 @@ ac_help="$ac_help
 ac_help="$ac_help
   --enable-debug 	  enable debugging [yes]"
 ac_help="$ac_help
-    --enable-dynamic	  enable linking built binaries with dynamic libs [no]"
-ac_help="$ac_help
   --enable-syslog	  enable syslog support [auto]"
+ac_help="$ac_help
+  --enable-dynamic	  enable linking built binaries with dynamic libs [no]"
 ac_help="$ac_help
   --enable-proctitle	  enable proctitle support [yes]"
 ac_help="$ac_help
@@ -1408,26 +1408,6 @@ else
   	ol_enable_debug="yes"
 fi
 # end --enable-debug
-# OpenLDAP --enable-dynamic
-	# Check whether --enable-dynamic or --disable-dynamic was given.
-if test "${enable_dynamic+set}" = set; then
-  enableval="$enable_dynamic"
-  
-	ol_arg=invalid
-	for ol_val in auto yes no ; do
-		if test "$enableval" = "$ol_val" ; then
-			ol_arg="$ol_val"
-		fi
-	done
-	if test "$ol_arg" = "invalid" ; then
-		{ echo "configure: error: bad value $enableval for --enable-dynamic" 1>&2; exit 1; }
-	fi
-	ol_enable_dynamic="$ol_arg"
-
-else
-  	ol_enable_dynamic="no"
-fi
-# end --enable-dynamic
 # OpenLDAP --enable-syslog
 	# Check whether --enable-syslog or --disable-syslog was given.
 if test "${enable_syslog+set}" = set; then
@@ -1448,6 +1428,26 @@ else
   	ol_enable_syslog="auto"
 fi
 # end --enable-syslog
+# OpenLDAP --enable-dynamic
+	# Check whether --enable-dynamic or --disable-dynamic was given.
+if test "${enable_dynamic+set}" = set; then
+  enableval="$enable_dynamic"
+  
+	ol_arg=invalid
+	for ol_val in auto yes no ; do
+		if test "$enableval" = "$ol_val" ; then
+			ol_arg="$ol_val"
+		fi
+	done
+	if test "$ol_arg" = "invalid" ; then
+		{ echo "configure: error: bad value $enableval for --enable-dynamic" 1>&2; exit 1; }
+	fi
+	ol_enable_dynamic="$ol_arg"
+
+else
+  	ol_enable_dynamic="no"
+fi
+# end --enable-dynamic
 # OpenLDAP --enable-proctitle
 	# Check whether --enable-proctitle or --disable-proctitle was given.
 if test "${enable_proctitle+set}" = set; then
