Add a little boldness

diff --git a/tests/scripts/all b/tests/scripts/all
--- a/tests/scripts/all
+++ b/tests/scripts/all
@@ -22,17 +22,22 @@ fi
 
 echo ">>>>> Backend: $BACKEND"
 
+SHTOOL="$SRCDIR/../build/shtool"
+
+TB=`$SHTOOL echo -e "%B"`
+TN=`$SHTOOL echo -e "%b"`
+
 for CMD in $SRCDIR/scripts/test*; do
-	echo ">>>>> Starting `basename $CMD` ..."
+	echo ">>>>> Starting ${TB}`basename $CMD`${TN} ..."
 	$CMD $SRCDIR $BACKEND
 	RC=$?
 	if test $RC -eq 0 ; then
-		echo ">>>>> $CMD completed OK."
+		echo ">>>>> $CMD completed ${TB}OK${TN}."
 	else
-		echo ">>>>> $CMD failed (exit $RC)"
+		echo ">>>>> $CMD ${TB}failed${TN} (exit $RC)"
 		exit $RC
 	fi
 	echo ">>>>> waiting 10 seconds for things to exit"
 	sleep 10
-	echo
+	echo ""
 done
