Suck in changes from HEAD     Fix slapd schema error alignment bug     Update slapd SASL proxy policy code     Update slapd require "strong" check     Update back-bdb entry locking     Add slapd disallow bind_simple_unprotected directive     Add back-monitor added monitorContext support     Add slapd IPv4/v6 only options     Ass slapd SASL setpass support     Remove lint     Build Environment         Add monitor backend test         Update <ac/socket.h> SHUT_RDWR         Fix SASL-less build issues         Fix back-perl build issues

diff --git a/tests/scripts/all b/tests/scripts/all
--- a/tests/scripts/all
+++ b/tests/scripts/all
@@ -1,23 +1,49 @@
-#!/bin/sh
+#! /bin/sh
+# $OpenLDAP$
+
+# disable LDAP initialization
+LDAPNOINIT=true; export LDAPNOINIT
 
 echo ">>>>> Executing all LDAP tests..."
 
-if [ $# -eq 0 ]; then
-	SCRIPTDIR="."
+if test $# -eq 0 ; then
+	SRCDIR="."
 else
-	SCRIPTDIR=$1; shift
+	SRCDIR=$1; shift
 fi
 
-for i in $SCRIPTDIR/test*; do
-	CMD=$i $*
-	echo ">>>>> Starting $CMD ..."
-	$CMD
+echo ">>>>> Test Directory: $SRCDIR"
+
+if test $# -eq 0 ; then
+	BACKEND=bdb
+else
+	BACKEND=$1; shift
+fi
+
+echo ">>>>> Backend: $BACKEND"
+
+if test $# -eq 0 ; then
+	MONITOR=no
+else
+	MONITOR=$1; shift
+fi
+
+SHTOOL="$SRCDIR/../build/shtool"
+
+TB=`$SHTOOL echo -e "%B"`
+TN=`$SHTOOL echo -e "%b"`
+
+for CMD in $SRCDIR/scripts/test*; do
+	echo ">>>>> Starting ${TB}`basename $CMD`${TN} ..."
+	$CMD $SRCDIR $BACKEND $MONITOR
 	RC=$?
-	if [ $RC -eq 0 ]; then
-		echo ">>>>> $CMD completed OK."
+	if test $RC -eq 0 ; then
+		echo ">>>>> $CMD completed ${TB}OK${TN}."
 	else
-		echo ">>>>> $CMD failed (exit $RC)"
+		echo ">>>>> $CMD ${TB}failed${TN} (exit $RC)"
 		exit $RC
 	fi
-	echo
+	echo ">>>>> waiting 10 seconds for things to exit"
+	sleep 10
+	echo ""
 done
diff --git a/tests/scripts/test001-slapadd b/tests/scripts/test001-slapadd
--- a/tests/scripts/test001-slapadd
+++ b/tests/scripts/test001-slapadd
@@ -1,30 +1,55 @@
-#!/bin/sh
+#! /bin/sh
+# $OpenLDAP$
 
-. scripts/defines.sh
+SRCDIR="."
+if test $# -ge 1 ; then
+	SRCDIR=$1; shift
+fi
+BACKEND=bdb
+if test $# -ge 1 ; then
+	BACKEND=$1; shift
+fi
+MONITORDB=no
+if test $# -ge 1 ; then
+	MONITORDB=$1; shift
+fi
+WAIT=0
+if test $# -ge 1 ; then
+	WAIT=1; shift
+fi
 
+echo "running defines.sh"
+. $SRCDIR/scripts/defines.sh
+
+echo "Datadir is $DATADIR"
 
 echo "Cleaning up in $DBDIR..."
 
-rm -f $DBDIR/*
+rm -f $DBDIR/[!C]*
 
-echo "Running ldif2ldbm to build slapd database..."
-$LDIF2LDBM -f $CONF -i $LDIF -e ../servers/slapd/tools
+echo "Running slapadd to build slapd database..."
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $ADDCONF
+$SLAPADD -f $ADDCONF -l $LDIFORDERED
 RC=$?
-if [ $RC != 0 ]; then
-	echo "ldif2ldbm failed!"
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
 	exit $RC
 fi
 
 echo "Starting slapd on TCP/IP port $PORT..."
-$SLAPD -f $CONF -p $PORT -d 1 > /dev/null 2>&1 &
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $DBCONF
+$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
 PID=$!
+if test $WAIT != 0 ; then
+    echo PID $PID
+    read foo
+fi
 
 echo "Using ldapsearch to retrieve all the entries..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-		'objectClass=*' > $SEARCHOUT 2>&1
+	$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT > $SEARCHOUT 2>&1
 	RC=$?
-	if [ $RC = 1 ]; then
+	if test $RC = 1 ; then
 		echo "Waiting 5 seconds for slapd to start..."
 		sleep 5
 	fi
@@ -32,15 +57,22 @@ done
 
 kill -HUP $PID
 
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	exit $RC
 fi
 
-echo "Comparing retrieved entries to LDIF file used to create database"
-cmp $SEARCHOUT $LDIF
-if [ $? != 0 ]; then
+echo "Filtering ldapsearch results..."
+. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+echo "Filtering original ldif used to create database..."
+. $LDIFFILTER < $LDIF > $LDIFFLT
+echo "Comparing filter output..."
+$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
+
+if test $? != 0 ; then
 	echo "comparison failed - database was not created correctly"
+	echo $SEARCHFLT $LDIFFLT
+	$DIFF $SEARCHFLT $LDIFFLT
 	exit 1
 fi
 
diff --git a/tests/scripts/test004-modify b/tests/scripts/test004-modify
--- a/tests/scripts/test004-modify
+++ b/tests/scripts/test004-modify
@@ -1,54 +1,86 @@
-#!/bin/sh
+#! /bin/sh
+# $OpenLDAP$
 
-. scripts/defines.sh
+SRCDIR="."
+if test $# -ge 1 ; then
+	SRCDIR=$1; shift
+fi
+BACKEND=bdb
+if test $# -ge 1 ; then
+	BACKEND=$1; shift
+fi
+MONITORDB=no
+if test $# -ge 1 ; then
+	MONITORDB=$1; shift
+fi
+WAIT=0
+if test $# -ge 1 ; then
+	WAIT=1; shift
+fi
+
+echo "running defines.sh"
+. $SRCDIR/scripts/defines.sh
+
+echo "running defines.sh $SRCDIR $BACKEND"
+. $SRCDIR/scripts/defines.sh
 
 echo "Cleaning up in $DBDIR..."
 
-rm -f $DBDIR/*
+rm -f $DBDIR/[!C]*
 
-echo "Running ldif2ldbm to build slapd database..."
-$LDIF2LDBM -f $CONF -i $LDIF -e ../servers/slapd/tools
+echo "Running slapadd to build slapd database..."
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $DBCONF
+$SLAPADD -f $DBCONF -l $LDIFORDERED
 RC=$?
-if [ $RC != 0 ]; then
-	echo "ldif2ldbm failed!"
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
 	exit $RC
 fi
 
 echo "Starting slapd on TCP/IP port $PORT..."
-$SLAPD -f $CONF -p $PORT -d 1 > /dev/null 2>&1 &
+$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
 PID=$!
+if test $WAIT != 0 ; then
+    echo PID $PID
+    read foo
+fi
 
 echo "Testing slapd modify operations..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-		'cn=Manager' > /dev/null 2>&1
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
+		'objectclass=*' > /dev/null 2>&1
 	RC=$?
-	if [ $RC = 1 ]; then
+	if test $RC = 1 ; then
 		echo "Waiting 5 seconds for slapd to start..."
 		sleep 5
 	fi
 done
 
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
-cat /dev/null > $TESTOUT
-
 echo "Testing modify, add, and delete..."
-$LDAPMODIFY -v -D "$MANAGERDN" -h localhost -p $PORT -w $PASSWD > \
-	/dev/null 2>&1 << EOMODS
-dn: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT -w $PASSWD > \
+	$TESTOUT 2>&1 << EOMODS
+version: 1
+
+# LEADING COMMENT AND WHITE SPACE
+
+dn: cn=James A Jones 1,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+# EMBEDDED COMMENT
 changetype: modify
 add: drink
 drink: Orange Juice
 
-dn: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
 changetype: modify
-replace: multilinedescription
-multilinedescription: The replaced multiLineDescription $ Blah Woof.
+# EMBEDDED COMMENT
+ CONTINUED
+replace: description
+description: The replaced multiLineDescription $ Blah Woof.
 -
 replace: drink
 drink: Iced Tea
@@ -56,71 +88,76 @@ drink: Mad Dog 20/20
 
 dn: cn=ITD Staff,ou=Groups,o=University of Michigan,c=US
 delete: member
-member: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
-member: cn=Bjorn Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+member: cn=James A Jones 2,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
+member: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
 -
 add: member
-member: cn=Dorothy Stevens, ou=Alumni Association, ou=People, o=University of Michigan, c=US
-member: cn=James A Jones 1, ou=Alumni Association, ou=People, o=University of Michigan, c=US
+member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,o=University of Michigan,c=US
+member: cn=James A Jones 1,ou=Alumni Association,ou=People,o=University of Michigan,c=US
 
 dn: cn=All Staff,ou=Groups,o=University of Michigan,c=US
 changetype: modify
 delete: member
+-
+add: member
+member: cn=Dorothy Stevens,ou=Alumni Association,ou=People,o=University of Michigan,c=US
 
-dn: cn=Gern Jensen, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=Gern Jensen,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
 changetype: add
 objectclass: top
 objectclass: person
-objectclass: organizationalPerson
-objectclass: newPilotPerson
-objectclass: umichPerson
+objectclass: OpenLDAPperson
 cn: Gern Jensen
+sn: Jensen
+uid: gjensen
 title: Chief Investigator, ITD
 postaladdress: ITD $ 535 W. William St $ Ann Arbor, MI 48103
-seealso: cn=All Staff, ou=Groups, o=University of Michigan, c=US
-uid: gjensen
-krbname: gjensen@umich.edu
-nobatchupdates: TRUE
-onvacation: FALSE
+seealso: cn=All Staff,ou=Groups,o=University of Michigan,c=US
 drink: Coffee
 homepostaladdress: 844 Brown St. Apt. 4 $ Ann Arbor, MI 48104
-multilinedescription: Very odd
+description: Very odd
 facsimiletelephonenumber: +1 313 555 7557
 telephonenumber: +1 313 555 8343
 mail: gjensen@mailgw.umich.edu
 homephone: +1 313 555 8844
 
-dn: cn=James A Jones 2, ou=Information Technology Division, ou=People, o=University of Michigan, c=US
+dn: cn=James A Jones 2,ou=Information Technology Division,ou=People,o=University of Michigan,c=US
 changetype: delete
+# TRAILING COMMENT AND WHITE SPACE
 
 EOMODS
 
 RC=$?
-if [ $RC != 0 ]; then
-	echo "ldapmodify failed!"
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
 echo "Using ldapsearch to retrieve all the entries..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	    'objectClass=*' | egrep -iv '^createtimestamp:|^modifytimestamp:' \
-	    > $SEARCHOUT 2>&1
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	    'objectClass=*' > $SEARCHOUT 2>&1
 RC=$?
 kill -HUP $PID
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	exit $RC
 fi
 
-echo "Comparing database to reference file"
-cmp $SEARCHOUT $MODIFYOUTMASTER
-if [ $? != 0 ]; then
+LDIF=$MODIFYOUTMASTER
+
+echo "Filtering ldapsearch results..."
+. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+echo "Filtering original ldif used to create database..."
+. $LDIFFILTER < $LDIF > $LDIFFLT
+echo "Comparing filter output..."
+$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
+
+if test $? != 0 ; then
 	echo "comparison failed - modify operations did not complete correctly"
 	exit 1
 fi
 
 echo ">>>>> Test succeeded"
-
 
 exit 0
