ITS#3144, ITS#3152 verify cache results

diff --git a/tests/scripts/test020-proxycache b/tests/scripts/test020-proxycache
--- a/tests/scripts/test020-proxycache
+++ b/tests/scripts/test020-proxycache
@@ -257,5 +257,13 @@ else
 	exit 1
 fi
 
+echo "Comparing cache output..."
+$CMP $SLAVEOUT $PROXYCACHEOUT > $CMPOUT
+
+if test $? != 0 ; then
+	echo "Comparison failed"
+	exit 1
+fi
+
 echo ">>>>> Test succeeded"
 exit 0
