add was failing because not compliant with schema

diff --git a/tests/scripts/test023-refint b/tests/scripts/test023-refint
--- a/tests/scripts/test023-refint
+++ b/tests/scripts/test023-refint
@@ -158,6 +158,7 @@ $LDAPADD -D "$REFINTDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
 	$TESTOUT 2>&1 << ETEST
 dn: uid=special,ou=users,o=refint
 objectClass: inetOrgPerson
+objectClass: extensibleObject
 uid: special
 sn: special
 cn: special
@@ -170,6 +171,13 @@ employeeType: vendor
 givenName: special
 member: uid=alice,ou=users,o=refint
 ETEST
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "Testing delete when referential attribute is a MUST..."
 $LDAPMODIFY -v -D "$REFINTDN" -h $LOCALHOST -p $PORT1 -w $PASSWD > \
