Check return of ldapadd(1)

diff --git a/tests/scripts/test026-dn b/tests/scripts/test026-dn
--- a/tests/scripts/test026-dn
+++ b/tests/scripts/test026-dn
@@ -50,6 +50,12 @@ fi
 echo "Loading database..."
 $LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD -c -f $LDIFDN > \
 	/dev/null 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "Searching database..."
 $LDAPSEARCH -b "$BASEDN" -h $LOCALHOST -p $PORT1 > $SEARCHOUT 2>&1
