Merge in all devel changes since 2.0-alpha2. Move OPENLDAP_REL_ENG_2_MP forward.

diff --git a/tests/scripts/test005-modrdn b/tests/scripts/test005-modrdn
--- a/tests/scripts/test005-modrdn
+++ b/tests/scripts/test005-modrdn
@@ -1,4 +1,5 @@
 #! /bin/sh
+# $OpenLDAP$
 
 if test $# -eq 0 ; then
 	SRCDIR="."
@@ -16,11 +17,11 @@ echo "Cleaning up in $DBDIR..."
 
 rm -f $DBDIR/[!C]*
 
-echo "Running ldif2ldbm to build slapd database..."
+echo "Running slapadd to build slapd database..."
 $LDIF2LDBM -f $CONF -l $LDIF
 RC=$?
 if test $RC != 0 ; then
-	echo "ldif2ldbm failed!"
+	echo "slapadd failed!"
 	exit $RC
 fi
 
@@ -31,8 +32,8 @@ echo "Testing slapd modrdn operations..."
 
 # Make sure we can search the database
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -s base -b "$MONITOR" -h localhost -p $PORT \
-		'objectclass=*' > /dev/null 2>&1
+	$LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
+	    'objectClass=*' > $INITOUT 2>&1
 	RC=$?
 	if test $RC = 1 ; then
 		echo "Waiting 5 seconds for slapd to start..."
@@ -74,8 +75,7 @@ fi
 
 echo "Using ldapsearch to retrieve entries using new rdn (cn=James A Jones III)..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
-	    'cn=James A Jones III' | egrep -iv '^createtimestamp:|^modifytimestamp:' \
-	    > $SEARCHOUT 2>&1
+	    'cn=James A Jones III' > $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed!"
@@ -102,8 +102,7 @@ fi
 
 echo "Using ldapsearch to retrieve entries using new rdn (cn=James A Jones II)..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
-	    'cn=James A Jones II' | egrep -iv '^createtimestamp:|^modifytimestamp:' \
-	    >  $SEARCHOUT 2>&1
+	    'cn=James A Jones II' > $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed!"
@@ -132,13 +131,18 @@ fi
 
 echo "Using ldapsearch to retrieve entries using removed rdn (cn=James A Jones 2)..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
-	    'cn=James A Jones 2' | egrep -iv '^createtimestamp:|^modifytimestamp:' \
-	    > /dev/null 2>&1
+	    'cn=James A Jones 2' > $SEARCHOUT 2>&1
 RC=$?
-if test $RC = 0 ; then
+if test $RC != 0 ; then
+	kill -HUP $PID
+	echo "ldapsearch failed!"
+	exit $RC
+fi
+cmp $SEARCHOUT /dev/null
+if test $? != 0 ; then
 	echo "failure: ldapsearch found attribute that was to be removed!"
 	kill -HUP $PID
-	exit $RC
+	exit 1
 fi
 
 echo "Using ldapsearch to retrieve all the entries..."
@@ -183,8 +187,7 @@ fi
 
 echo "Using ldapsearch to retrieve entries using new rdn (cn=James A Jones 1)..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
-	    'cn=James A Jones 1' | egrep -iv '^createtimestamp:|^modifytimestamp:' \
-	    >  $SEARCHOUT 2>&1
+	    'cn=James A Jones 1' > $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed!"
