Split manage test between working and non-working-yet cases

diff --git a/tests/scripts/test037-manage b/tests/scripts/test037-manage
--- a/tests/scripts/test037-manage
+++ b/tests/scripts/test037-manage
@@ -13,9 +13,6 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-echo "skipping test (not yet implemented)"
-exit 0
-
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
@@ -59,50 +56,50 @@ fi
 
 echo "Testing modify, add, and delete..."
 $LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
-	-e \!ManageDIT > \
+	-e \!manageDIT > \
 	$TESTOUT 2>&1 << EOMODS
 version: 1
+# Working Tests
 
-# LEADING COMMENT AND WHITE SPACE
+# ObjectClass tests
 
 dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
  dc=com
-# add obsolete objectclass
+# add obsolete auxiliary objectclass
 changetype: modify
 add: objectClass
 objectClass: obsoletePerson
--
+
+dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
+ dc=com
+# add obsolete attribute
+changetype: modify
 add: testObsolete
 testObsolete: TRUE
 
-dn: cn=James A Jones 1,ou=Alumni Association,ou=People,dc=example,dc=com
-# update structural object class of entry via objectClass replace
-changetype: modify
-replace: objectClass
-objectClass: testPerson
--
-replace: objectClass
-objectClass: structuralObjectClass
+EOMODS
 
-dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
-# update structural object class of entry via objectClass modify
-changetype: modify
-delete: objectClass
-objectClass: OpenLDAPperson
--
-add: objectClass
-objectClass: testPerson
--
-delete: structuralObjectClass
--
-add: objectClass
-objectClass: testPerson
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
-dn: cn=ITD Staff,ou=Groups,dc=example,dc=com
+echo "Testing modify, add, and delete..."
+$LDAPMODIFY -v -D "$MANAGERDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
+	-e \!manageDIT > \
+	$TESTOUT 2>&1 << EOMODS
+version: 1
+#
+# Non-working tests
+#
+
+#dn: cn=ITD Staff,ou=Groups,dc=example,dc=com
 # change entryUUID
-changetype: modify
-replace: entryUUID
-entryUUID: B51EE239-C24A-11D9-A541-000D9342AD1E
+#changetype: modify
+#replace: entryUUID
+#entryUUID: B51EE239-C24A-11D9-A541-000D9342AD1E
 
 dn: ou=Groups,dc=example,dc=com
 # change creatorsName
@@ -116,13 +113,46 @@ changetype: modify
 replace: modifiersName
 modifiersName: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
 
+dn: cn=Barbara Jensen,ou=Information Technology Division,ou=People,dc=example,
+ dc=com
+# update structural object class of entry via objectClass replace
+changetype: modify
+replace: objectClass
+objectClass: obsoletePerson
+-
+replace: structuralObjectClass
+structuralObjectClass: testPerson
+
+dn: cn=James A Jones 1,ou=Alumni Association,ou=People,dc=example,dc=com
+# update structural object class of entry via objectClass add
+changetype: modify
+add: objectClass
+objectClass: testPerson
+-
+replace: structuralObjectClass
+structuralObjectClass: testPerson
+
+dn: cn=Bjorn Jensen,ou=Information Technology Division,ou=People,dc=example,dc=com
+# update structural object class of entry via objectClass delete/add
+changetype: modify
+delete: objectClass
+objectClass: OpenLDAPperson
+-
+add: objectClass
+objectClass: testPerson
+-
+delete: structuralObjectClass
+-
+add: structuralObjectClass
+structuralObjectClass: testPerson
+
 EOMODS
 
 RC=$?
 if test $RC != 0 ; then
-	echo "ldapmodify failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
+	echo "ldapmodify failed ($RC)!  IGNORED"
+#	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+#	exit $RC
 fi
 
 echo "Using ldapsearch to retrieve all the entries..."
@@ -135,7 +165,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-LDIF=$MODIFYOUTMASTER
+LDIF=$MANAGEOUT
 
 echo "Filtering ldapsearch results..."
 . $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
