Suck in HEAD changes since 2.1alpha

diff --git a/tests/scripts/test003-search b/tests/scripts/test003-search
--- a/tests/scripts/test003-search
+++ b/tests/scripts/test003-search
@@ -1,84 +1,119 @@
-#!/bin/sh
+#! /bin/sh
+# $OpenLDAP$
 
-. scripts/defines.sh
+SRCDIR="."
+if test $# -ge 1 ; then
+	SRCDIR=$1; shift
+fi
+BACKEND=bdb
+if test $# -ge 1 ; then
+	BACKEND=$1; shift
+fi
+WAIT=0
+if test $# -ge 1 ; then
+	WAIT=1; shift
+fi
+
+echo "running defines.sh"
+. $SRCDIR/scripts/defines.sh
 
 echo "Cleaning up in $DBDIR..."
 
-rm -f $DBDIR/*
+rm -f $DBDIR/[!C]*
 
-echo "Running ldif2ldbm to build slapd database..."
-$LDIF2LDBM -f $CONF -i $LDIF -e ../servers/slapd/tools
+echo "Running slapadd to build slapd database..."
+. $CONFFILTER $BACKEND < $MCONF > $ADDCONF
+$SLAPADD -f $ADDCONF -l $LDIFORDERED
 RC=$?
-if [ $RC != 0 ]; then
-	echo "ldif2ldbm failed!"
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
 	exit $RC
 fi
 
+echo "Running slapindex to index slapd database..."
+. $CONFFILTER $BACKEND < $CONF > $DBCONF
+$SLAPINDEX -f $DBCONF
+RC=$?
+if test $RC != 0 ; then
+	echo "warning: slapindex failed ($RC)"
+	echo "  assuming no indexing support"
+fi
+
 echo "Starting slapd on TCP/IP port $PORT..."
-$SLAPD -f $CONF -p $PORT -d 1 > /dev/null 2>&1 &
+$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
 PID=$!
+if test $WAIT != 0 ; then
+    echo PID $PID
+    read foo
+fi
 
 echo "Testing slapd searching..."
 for i in 0 1 2 3 4 5; do
-	$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-		'cn=Manager' > /dev/null 2>&1
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
+		'objectclass=*' > /dev/null 2>&1
 	RC=$?
-	if [ $RC = 1 ]; then
+	if test $RC = 1 ; then
 		echo "Waiting 5 seconds for slapd to start..."
 		sleep 5
 	fi
 done
 
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
-cat /dev/null > $TESTOUT
+cat /dev/null > $SEARCHOUT
 
 echo "Testing exact searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'sn=jensen' >> $TESTOUT 2>&1
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'sn=jensen' >> $SEARCHOUT 2>&1
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
 echo "Testing OR searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'(|(objectclass=rfc822mailgroup)(sn=jones))' >> $TESTOUT 2>&1
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'(|(givenName=XX*YY*Z)(cn=)(undef=*)(objectclass=groupofnames)(sn=jones))' >> $SEARCHOUT 2>&1
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
 echo "Testing AND matching and ends-with searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'(&(objectclass=rfc822mailgroup)(cn=A*))' >> $TESTOUT 2>&1
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'(&(objectclass=groupofnames)(cn=A*))' >> $SEARCHOUT 2>&1
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
 echo "Testing NOT searching..."
-$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
-	'(!(objectclass=person))' | grep -v "^modifytimestamp:" \
-	>> $TESTOUT 2>&1
-if [ $RC != 0 ]; then
-	echo "ldapsearch failed!"
+$LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'(!(objectclass=pilotPerson))' >> $SEARCHOUT 2>&1
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
 	kill -HUP $PID
 	exit $RC
 fi
 
 kill -HUP $PID
 
-echo "Comparing results"
-cmp $TESTOUT $SEARCHOUTMASTER
-if [ $? != 0 ]; then
+LDIF=$SEARCHOUTMASTER
+
+echo "Filtering ldapsearch results..."
+. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
+echo "Filtering original ldif used to create database..."
+. $LDIFFILTER < $LDIF > $LDIFFLT
+echo "Comparing filter output..."
+$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
+
+if test $? != 0 ; then
 	echo "Comparison failed"
 	exit 1
 fi
