take care of the (yet unpublished) evolution of <draft-zeilenga-ldap-assert>

diff --git a/tests/scripts/test033-glue-syncrepl b/tests/scripts/test033-glue-syncrepl
--- a/tests/scripts/test033-glue-syncrepl
+++ b/tests/scripts/test033-glue-syncrepl
@@ -20,7 +20,19 @@ fi
 echo "running defines.sh"
 . $SRCDIR/scripts/defines.sh
 
-mkdir -p $TESTDIR $DBDIR1A $DBDIR1B $DBDIR1C $DBDIR2A $DBDIR2B $DBDIR2C
+mkdir -p $TESTDIR $DBDIR1A $DBDIR1B $DBDIR1C $DBDIR2A $DBDIR2B
+
+echo "Running slapadd to build glued slapd databases..."
+. $CONFFILTER $BACKEND $MONITORDB < $GLUECONF > $CONF1
+$SLAPADD -d $LVL -f $CONF1 -l $LDIFORDERED > $SLAPADDLOG1 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
+rm -f $DBDIR1A/* $DBDIR1B/*
+cp -pr $DBDIR1C $DBDIR2C
 
 echo "Starting slapd 1 on TCP/IP port $PORT1..."
 . $CONFFILTER $BACKEND $MONITORDB < $GLUESYNCCONF1 > $CONF1
@@ -73,39 +85,9 @@ done
 SUBTREE1="ou=Information Technology Division,ou=People,dc=example,dc=com"
 SUBTREE2="ou=Groups,dc=example,dc=com"
 
-for M in 1 2 ; do
-	P=`expr 9010 + $M`
-	echo "Using ldapadd to populate the common root on port $P..."
-	$LDAPADD -D "cn=Manager $M,$BASEDN" -w $PASSWD -h $LOCALHOST -p $P \
-		-f $LDIFORDERED \
-		-c -e\!assert="(&(!(entryDN:dnSubtreeMatch:=${SUBTREE1}))(!(entryDN:dnSubtreeMatch:=${SUBTREE2})))" \
-		> /dev/null 2>&1
-	RC=$?
-	case $RC in
-	0)
-		echo "ldapadd should have failed ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit -1
-		;;
-	10|32|68)
-		# FIXME: we should rather get ASSERT, and ignore it;
-		# see <http://www.openldap.org/lists/openldap-software/200512/msg00250.html>
-		# for details.
-		# Fine by now if we get noSuchObject, alreadyExists
-		# or referrals
-		;;
-	*)
-		echo "ldapadd failed ($RC)!"
-		test $KILLSERVERS != no && kill -HUP $KILLPIDS
-		exit $RC
-		;;
-	esac
-done
-
 echo "Using ldapadd to populate subtree=\"${SUBTREE1}\" on port $PORT1..."
 $LDAPADD -D "cn=Manager 1,$BASEDN" -w $PASSWD -h $LOCALHOST -p $PORT1 \
-	-f $LDIFORDERED \
-	-c -e\!assert="(entryDN:dnSubtreeMatch:=${SUBTREE1})" \
+	-f $LDIFORDERED -c \
 	> /dev/null 2>&1
 RC=$?
 case $RC in
@@ -114,12 +96,8 @@ case $RC in
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
 	;;
-10|32|68)
-	# FIXME: we should rather get ASSERT, and ignore it;
-	# see <http://www.openldap.org/lists/openldap-software/200512/msg00250.html>
-	# for details.
-	# Fine by now if we get noSuchObject, alreadyExists
-	# or referrals
+10|68)
+	# Fine if we get alreadyExists or referrals
 	;;
 *)
 	echo "ldapadd failed ($RC)!"
@@ -130,8 +108,7 @@ esac
 
 echo "Using ldapadd to populate subtree=\"${SUBTREE2}\" on port $PORT2..."
 $LDAPADD -D "cn=Manager 2,$BASEDN" -w $PASSWD -h $LOCALHOST -p $PORT2 \
-	-f $LDIFORDERED \
-	-c -e\!assert="(entryDN:dnSubtreeMatch:=${SUBTREE2})" \
+	-f $LDIFORDERED -c \
 	> /dev/null 2>&1
 RC=$?
 case $RC in
@@ -140,12 +117,8 @@ case $RC in
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit -1
 	;;
-10|32|68)
-	# FIXME: we should rather get ASSERT, and ignore it;
-	# see <http://www.openldap.org/lists/openldap-software/200512/msg00250.html>
-	# for details.
-	# Fine by now if we get noSuchObject, alreadyExists
-	# or referrals
+10|68)
+	# Fine if we get alreadyExists or referrals
 	;;
 *)
 	echo "ldapadd failed ($RC)!"
