ITS#9038 Update test028 to test this is enforced

diff --git a/tests/scripts/test028-idassert b/tests/scripts/test028-idassert
--- a/tests/scripts/test028-idassert
+++ b/tests/scripts/test028-idassert
@@ -191,6 +191,17 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+AUTHZID="u:it/jaj"
+echo "Checking another DB's rootdn can't assert identity from another DB..."
+$LDAPWHOAMI -h $LOCALHOST -p $PORT1 -D "$MANAGERDN" -w $PASSWD -e\!"authzid=$AUTHZID"
+
+RC=$?
+if test $RC != 1 ; then
+    echo "ldapwhoami should have failed ($RC)!"
+    test $KILLSERVERS != no && kill -HUP $KILLPIDS
+    exit $RC
+fi
+
 ID="uid=jaj,ou=People,dc=example,dc=it"
 BASE="o=Example,c=US"
 echo "Testing ldapsearch as $ID for \"$BASE\"..."
@@ -227,6 +238,19 @@ if test $USE_SASL != "no" ; then
 	RC=$?
 	if test $RC != 0 ; then
 		echo "ldapsearch failed ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	fi
+
+	ID="manager"
+	AUTHZID="u:it/jaj"
+	echo "Checking another DB's rootdn can't assert in another (with SASL bind this time)..."
+	$LDAPSASLWHOAMI -h $LOCALHOST -p $PORT1 \
+		-Q -U "$ID" -w $PASSWD -Y $MECH -X $AUTHZID
+
+	RC=$?
+	if test $RC != 50 ; then
+		echo "ldapwhoami should have failed ($RC)!"
 		test $KILLSERVERS != no && kill -HUP $KILLPIDS
 		exit $RC
 	fi
