Import latest from devel

diff --git a/tests/scripts/test003-search b/tests/scripts/test003-search
--- a/tests/scripts/test003-search
+++ b/tests/scripts/test003-search
@@ -18,10 +18,18 @@ echo "Cleaning up in $DBDIR..."
 rm -f $DBDIR/[!C]*
 
 echo "Running slapadd to build slapd database..."
-$LDIF2LDBM -f $CONF -l $LDIF
+$SLAPADD -f $MCONF -l $LDIF
 RC=$?
 if test $RC != 0 ; then
 	echo "slapadd failed ($RC)!"
+	exit $RC
+fi
+
+echo "Running slapindex to index slapd database..."
+$SLAPINDEX -f $CONF
+RC=$?
+if test $RC != 0 ; then
+	echo "slapindex failed ($RC)!"
 	exit $RC
 fi
 
@@ -93,7 +101,7 @@ echo "Filtering ldapsearch results..."
 echo "Filtering original ldif used to create database..."
 . $SRCDIR/scripts/acfilter.sh < $LDIF > $LDIFFLT
 echo "Comparing filter output..."
-$CMP $SEARCHFLT $LDIFFLT
+$CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 
 if test $? != 0 ; then
 	echo "Comparison failed"
