For test063
add hex timestamp to lutil_debug() output
Fix LASTMOD race condition in accesslog.c
Set refreshInterval even if using refreshAndPersist, since
fallbacks will use refresh params

diff --git a/tests/scripts/test063-delta-multimaster b/tests/scripts/test063-delta-multimaster
--- a/tests/scripts/test063-delta-multimaster
+++ b/tests/scripts/test063-delta-multimaster
@@ -42,7 +42,7 @@ case "$SYNCMODE" in
 		SYNCTYPE="type=refreshOnly interval=00:00:00:03"
 		;;
 	rp)
-		SYNCTYPE="type=refreshAndPersist"
+		SYNCTYPE="type=refreshAndPersist interval=00:00:00:03"
 		;;
 	*)
 		echo "unknown sync mode $SYNCMODE"
@@ -288,8 +288,26 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
-sleep $SLEEP1
+THEDN="cn=James A Jones 2,ou=Alumni Association,ou=People,dc=example,dc=com"
+sleep 1
+for i in 1 2 3; do
+	$LDAPSEARCH -S "" -b "$THEDN" -H $URI1 \
+		-s base '(objectClass=*)' entryCSN > "${MASTEROUT}.$i" 2>&1
+	RC=$?
+
+	if test $RC = 0 ; then
+		break
+	fi
+
+	if test $RC != 32 ; then
+		echo "ldapsearch failed at slave ($RC)!"
+		test $KILLSERVERS != no && kill -HUP $KILLPIDS
+		exit $RC
+	fi
+
+	echo "Waiting $SLEEP1 seconds for syncrepl to receive changes..."
+	sleep $SLEEP1
+done
 
 n=1
 while [ $n -le $MMR ]; do
@@ -353,7 +371,6 @@ n=`expr $n + 1`
 done
 
 echo "Using ldapmodify to force conflicts between server 1 and 2..."
-THEDN="cn=James A Jones 2,ou=Alumni Association,ou=People,dc=example,dc=com"
 $LDAPMODIFY -D "$MANAGERDN" -H $URI1 -w $PASSWD \
 	>> $TESTOUT 2>&1 << EOF
 dn: $THEDN
