Finish adding subclassing indexing support

diff --git a/tests/scripts/test003-search b/tests/scripts/test003-search
--- a/tests/scripts/test003-search
+++ b/tests/scripts/test003-search
@@ -54,7 +54,7 @@ fi
 echo "Testing slapd searching..."
 for i in 0 1 2 3 4 5; do
 	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
-		'objectclass=*' > /dev/null 2>&1
+		'(objectclass=*)' > /dev/null 2>&1
 	RC=$?
 	if test $RC = 1 ; then
 		echo "Waiting 5 seconds for slapd to start..."
@@ -72,7 +72,7 @@ cat /dev/null > $SEARCHOUT
 
 echo "Testing exact searching..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
-	'sn=jensen' >> $SEARCHOUT 2>&1
+	'(sn=jensen)' >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
@@ -104,14 +104,25 @@ echo "Testing NOT searching..."
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
 	'(!(objectclass=pilotPerson))' >> $SEARCHOUT 2>&1
 RC=$?
-
-kill -HUP $PID
-
 if test $RC != 0 ; then
 	echo "ldapsearch failed ($RC)!"
+	kill -HUP $PID
 	exit $RC
 fi
 
+echo "Testing objectClass/attributeType inheritance ..."
+$LDAPSEARCH -M -a never -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT \
+	'(&(objectClass=inetorgperson)(uid=uham))' \
+	"2.5.4.0" "userid" >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapsearch failed ($RC)!"
+	kill -HUP $PID
+	exit $RC
+fi
+
+
+kill -HUP $PID
 LDIF=$SEARCHOUTMASTER
 
 echo "Filtering ldapsearch results..."
