ITS#9121 - Use memberOf instead of dgMemberOf

diff --git a/tests/scripts/test044-dynlist b/tests/scripts/test044-dynlist
--- a/tests/scripts/test044-dynlist
+++ b/tests/scripts/test044-dynlist
@@ -317,6 +317,13 @@ olcDynListAttrSet: groupOfURLs memberURL sn:cn mail
 -
 EOMODS
 
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "==========================================================" >> $LOG1
 
 echo "Testing attribute mapping"
@@ -426,6 +433,13 @@ add: olcDynListAttrSet
 olcDynListAttrSet: groupOfURLs memberURL member
 -
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "==========================================================" >> $LOG1
 
@@ -621,6 +635,13 @@ olcAccess: to dn.base="cn=Dynamic List of Members,$LISTDN" by * read
 olcAccess: to * by users read by * search
 EOMODS
 
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Testing list search without dgIdentity..."
 echo "# Testing list search without dgIdentity..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$LISTDN" -h $LOCALHOST -p $PORT1 \
@@ -644,6 +665,13 @@ add: dgIdentity
 dgIdentity: $CMPDN
 EOMODS
 
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Testing list search with dgIdentity..."
 echo "# Testing list search with dgIdentity..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$LISTDN" -h $LOCALHOST -p $PORT1 \
@@ -666,6 +694,13 @@ changetype: modify
 add: dgAuthz
 dgAuthz: dn:$BABSDN
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "Testing list search with dgIdentity and dgAuthz anonymously..."
 echo "# Testing list search with dgIdentity and dgAuthz anonymously..." >> $SEARCHOUT
@@ -702,9 +737,16 @@ delete: olcDynListAttrSet
 olcDynListAttrSet: {0}
 -
 add: olcDynListAttrSet
-olcDynListAttrSet: groupOfURLs memberURL member+dgMemberOf
+olcDynListAttrSet: groupOfURLs memberURL member+memberOf
 -
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "==========================================================" >> $LOG1
 
@@ -712,7 +754,7 @@ echo "Testing memberOf functionality..."
 echo "# Testing memberOf functionality..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(cn=Mark Elliot)' '*' \
+	'(cn=Mark Elliot)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -725,7 +767,7 @@ echo "Testing filtered memberOf functionality..."
 echo "# Testing filtered memberOf functionality..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(&(dgMemberOf=cn=Dynamic List of Members,ou=Dynamic Lists,dc=example,dc=com)(cn=Mark Elliot))' '*' \
+	'(&(memberOf=cn=Dynamic List of Members,ou=Dynamic Lists,dc=example,dc=com)(cn=Mark Elliot))' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -744,9 +786,16 @@ delete: olcDynListAttrSet
 olcDynListAttrSet: {0}
 -
 add: olcDynListAttrSet
-olcDynListAttrSet: groupOfURLs memberURL member+dgMemberOf@groupOfNames
+olcDynListAttrSet: groupOfURLs memberURL member+memberOf@groupOfNames
 -
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "==========================================================" >> $LOG1
 
@@ -754,7 +803,7 @@ echo "Testing static group memberOf functionality..."
 echo "# Testing static group memberOf functionality..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(cn=Mark Elliot)' '*' \
+	'(cn=Mark Elliot)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -773,9 +822,16 @@ delete: olcDynListAttrSet
 olcDynListAttrSet: {0}
 -
 add: olcDynListAttrSet
-olcDynListAttrSet: groupOfURLs memberURL member+dgMemberOf*
+olcDynListAttrSet: groupOfURLs memberURL member+memberOf*
 -
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "==========================================================" >> $LOG1
 
@@ -794,11 +850,18 @@ cn: Meta Group
 memberURL: ldap:///${LISTDN}??sub?(description=Smith%20family)
 EOMODS
 
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Testing nested dynamic group functionality..."
 echo "# Testing nested dynamic group functionality..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "$LISTDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(objectclass=*)' '*' \
+	'(objectclass=*)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -809,7 +872,7 @@ fi
 
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(cn=Mark Elliot)' '*' \
+	'(cn=Mark Elliot)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -828,10 +891,17 @@ delete: olcDynListAttrSet
 olcDynListAttrSet: {0}
 -
 add: olcDynListAttrSet
-olcDynListAttrSet: groupOfURLs memberURL member+dgMemberOf@groupOfNames*
+olcDynListAttrSet: groupOfURLs memberURL member+memberOf@groupOfNames*
 olcDynListAttrSet: labeledURIObject labeledURI uniqueMember+seeAlso@groupOfUniqueNames
 -
 EOMODS
+
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapmodify failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
 
 echo "==========================================================" >> $LOG1
 
@@ -852,11 +922,18 @@ member: cn=James A Jones 2,ou=Information Technology Division,ou=People,$BASEDN
 member: cn=The Jensens,ou=Groups,$BASEDN
 EOMODS
 
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Testing nested static group functionality..."
 echo "# Testing nested static group functionality..." >> $SEARCHOUT
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(sn=Jensen)' '*' \
+	'(sn=Jensen)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -877,7 +954,7 @@ EOMODS
 
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(sn=Hampster)' '*' \
+	'(sn=Hampster)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -888,7 +965,7 @@ fi
 
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(sn=Doe)' '*' \
+	'(sn=Doe)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -899,7 +976,7 @@ fi
 
 $LDAPSEARCH -S "" -b "ou=People,$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	'(sn=Smith)' '*' \
+	'(sn=Smith)' '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -913,7 +990,7 @@ echo "# Testing filtered nested memberOf functionality..." >> $SEARCHOUT
 
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	"(dgMemberOf=cn=bonus group,ou=groups,$BASEDN)" '*' \
+	"(memberOf=cn=bonus group,ou=groups,$BASEDN)" '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -927,7 +1004,7 @@ echo "# Testing filtered nested member functionality..." >> $SEARCHOUT
 
 $LDAPSEARCH -S "" -b "$BASEDN" -h $LOCALHOST -p $PORT1 \
 	-D "$BABSDN" -w bjensen \
-	"(member=cn=Jennifer Smith,ou=Alumni Association,ou=People,$BASEDN)" '*' \
+	"(member=cn=Jennifer Smith,ou=Alumni Association,ou=People,$BASEDN)" '*' 'memberOf' \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
