add test035 for back-meta; minor clanup to test030

diff --git a/tests/scripts/test035-meta b/tests/scripts/test035-meta
--- a/tests/scripts/test035-meta
+++ b/tests/scripts/test035-meta
@@ -13,11 +13,22 @@
 ## top-level directory of the distribution or, alternatively, at
 ## <http://www.OpenLDAP.org/license.html>.
 
-echo "Using $RELAY backend..."
+echo "running defines.sh"
+. $SRCDIR/scripts/defines.sh
+
 echo ""
 
+if test $BACKMETA = metano ; then 
+	echo "meta backend not available, test skipped"
+	exit 0
+fi
+
+rm -rf $TESTDIR
+
+mkdir -p $TESTDIR $DBDIR1 $DBDIR2
+
 echo "Starting slapd on TCP/IP port $PORT1..."
-. $CONFFILTER $BACKEND $MONITORDB < $RELAYCONF > $CONF1
+. $CONFFILTER $BACKEND $MONITORDB < $CONF > $CONF1
 $SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
 PID=$!
 if test $WAIT != 0 ; then
@@ -53,45 +64,49 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-cat /dev/null > $SEARCHOUT
+echo "Starting slapd on TCP/IP port $PORT2..."
+. $CONFFILTER $BACKEND $MONITORDB < $METACONF > $CONF2
+$SLAPD -f $CONF2 -h $URI2 -d $LVL $TIMING > $LOG2 2>&1 &
+PID=$!
+if test $WAIT != 0 ; then
+    echo PID $PID
+    read foo
+fi
+KILLPIDS="$KILLPIDS $PID"
 
-BASEDN="dc=example,dc=com"
-echo "Searching base=\"$BASEDN\"..."
-echo "# searching base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
-RC=$?
+echo "Using ldapsearch to check that slapd is running..."
+for i in 0 1 2 3 4 5; do
+	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT2 \
+		'objectclass=*' > /dev/null 2>&1
+	RC=$?
+	if test $RC = 0 ; then
+		break
+	fi
+	echo "Waiting 5 seconds for slapd to start..."
+	sleep 5
+done
 if test $RC != 0 ; then
-	echo "Search failed ($RC)!"
+	echo "ldapsearch failed ($RC)!"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit $RC
 fi
+
+echo "Using ldapadd to populate the database..."
+$LDAPADD -D "$METAMANAGERDN" -h $LOCALHOST -p $PORT2 -w $PASSWD < \
+	$LDIFMETA >> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "ldapadd failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+cat /dev/null > $SEARCHOUT
 
 BASEDN="o=Example,c=US"
 echo "Searching base=\"$BASEDN\"..."
 echo "# searching base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
-RC=$?
-if test $RC != 0 ; then
-	echo "Search failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-BASEDN="o=Esempio,c=IT"
-echo "Searching base=\"$BASEDN\"..."
-echo "# searching base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
-RC=$?
-if test $RC != 0 ; then
-	echo "Search failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-BASEDN="o=Beispiel,c=DE"
-echo "Searching base=\"$BASEDN\"..."
-echo "# searching base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT2 -b "$BASEDN" >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "Search failed ($RC)!"
@@ -103,89 +118,9 @@ fi
 # Do some modifications
 #
 
-BASEDN="o=Beispiel,c=DE"
-echo "Modifying database \"$BASEDN\"..."
-$LDAPMODIFY -v -D "cn=Manager,$BASEDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
-	-M >> $TESTOUT 2>&1 << EOMODS
-dn: cn=Added User,ou=Alumni Association,ou=People,$BASEDN
-changetype: add
-objectClass: OpenLDAPperson
-cn: Added User
-sn: User
-uid: auser
-seealso: cn=All Staff,ou=Groups,$BASEDN
-homephone: +49 1234567890
-drink: Beer
-mail: auser@mail.alumni.example.com
-telephonenumber: +49 1234-567-890
-description: Just added in o=Beispiel,c=DE naming context
-
-dn: cn=Ursula Hampster,ou=Alumni Association,ou=People,$BASEDN
-changetype: modify
-add: seeAlso
-seeAlso: cn=Ursula Hampster,ou=Alumni Association,ou=People,$BASEDN
--
-add: description
-description: Just added self to seeAlso in $BASEDN virtual naming context
--
-
-dn: cn=Mark Elliot,ou=Alumni Association,ou=People,$BASEDN
-changetype: delete
-
-dn: cn=John Doe,ou=Information Technology Division,ou=People,$BASEDN
-changetype: modrdn
-newrdn: cn=John P. Doe
-deleteoldrdn: 1
-
-dn: cn=Jane Doe,ou=Alumni Association,ou=People,$BASEDN
-changetype: modrdn
-newrdn: cn=Jane Q. Doe
-deleteoldrdn: 1
-newsuperior: ou=Information Technology Division,ou=People,$BASEDN
-
-dn: cn=Jane Q. Doe,ou=Information Technology Division,ou=People,$BASEDN
-changetype: modify
-add: cn
-cn: Jane Qissapaolo Doe
--
-# This operation (delete of DN-valued attribute) triggered ITS#3498
-delete: seeAlso
--
-
-dn: cn=Jane Q. Doe,ou=Information Technology Division,ou=People,$BASEDN
-changetype: modify
-add: seeAlso
-seeAlso: cn=All Staff,ou=Groups,$BASEDN
--
-
-dn: ou=Referrals,$BASEDN
-changetype: add
-objectclass: referral
-objectclass: extensibleObject
-ou: Referrals
-ref: ldap://localhost.localdomain/ou=Referrals,$BASEDN
-description: Just added as ldap://localhost.localdomain:389/ou=Referrals,$BASEDN
-
-dn: ou=Referrals,$BASEDN
-changetype: modify
-replace: ref
-ref: ldap://localhost:9010/ou=Referrals,$BASEDN
--
-add: description
-description: ...and modified as ldap://localhost:9010/ou=Referrals,$BASEDN
--
-EOMODS
-
-RC=$?
-if test $RC != 0 ; then
-	echo "Modify failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
 BASEDN="o=Example,c=US"
 echo "Modifying database \"$BASEDN\"..."
-$LDAPMODIFY -v -D "cn=Manager,$BASEDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
+$LDAPMODIFY -v -D "cn=Manager,$BASEDN" -h $LOCALHOST -p $PORT2 -w $PASSWD \
 	-M >> $TESTOUT 2>&1 << EOMODS
 # These operations (updates with objectClass mapping) triggered ITS#3499
 dn: cn=Added Group,ou=Groups,$BASEDN
@@ -219,6 +154,53 @@ objectClass: uidObject
 -
 delete: uid
 -
+
+dn: ou=Meta,$BASEDN
+changetype: modify
+add: description
+description: added to "ou=Meta,$BASEDN"
+-
+
+dn: ou=Who's going to handle this?,$BASEDN
+changetype: add
+objectClass: organizationalUnit
+ou: Who's going to handle this?
+description: added
+description: will be deleted
+
+dn: ou=Same as above,$BASEDN
+changetype: add
+objectClass: organizationalUnit
+ou: Same as above
+description: added right after "Who's going to handle this?"
+description: will be preserved
+
+dn: ou=Who's going to handle this?,$BASEDN
+changetype: delete
+
+dn: ou=Who's going to handle this?,ou=Meta,$BASEDN
+changetype: add
+objectClass: organizationalUnit
+ou: Who's going to handle this?
+description: added
+description: will be deleted
+
+dn: ou=Same as above,ou=Meta,$BASEDN
+changetype: add
+objectClass: organizationalUnit
+ou: Same as above
+description: added right after "Who's going to handle this?"
+description: will be preserved
+
+dn: cn=Added User,ou=Same as above,ou=Meta,$BASEDN
+changetype: add
+objectClass: inetOrgPerson
+cn: Added User
+sn: User
+userPassword: secret
+
+dn: ou=Who's going to handle this?,ou=Meta,$BASEDN
+changetype: delete
 EOMODS
 
 RC=$?
@@ -230,36 +212,7 @@ fi
 
 echo "Searching base=\"$BASEDN\"..."
 echo "# searching base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
-RC=$?
-if test $RC != 0 ; then
-	echo "Search failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-BASEDN="o=Esempio,c=IT"
-echo "Searching base=\"$BASEDN\"..."
-echo "# searching base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
-RC=$?
-if test $RC != 0 ; then
-	echo "Search failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-FILTER="(objectClass=referral)"
-echo "Searching filter=\"$FILTER\""
-echo "	attrs=\"'*' ref\""
-echo "# searching filter=\"$FILTER\"" >> $SEARCHOUT
-echo "# 	attrs=\"'*' ref\"" >> $SEARCHOUT
-
-BASEDN="dc=example,dc=com"
-echo "	base=\"$BASEDN\"..."
-echo "# 	base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" -M "$FILTER" '*' ref \
-	>> $SEARCHOUT 2>&1
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT2 -b "$BASEDN" >> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "Search failed ($RC)!"
@@ -270,19 +223,7 @@ fi
 BASEDN="o=Example,c=US"
 echo "	base=\"$BASEDN\"..."
 echo "# 	base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" -M "$FILTER" '*' ref \
-	>> $SEARCHOUT 2>&1
-RC=$?
-if test $RC != 0 ; then
-	echo "Search failed ($RC)!"
-	test $KILLSERVERS != no && kill -HUP $KILLPIDS
-	exit $RC
-fi
-
-BASEDN="o=Esempio,c=IT"
-echo "	base=\"$BASEDN\"..."
-echo "# 	base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" -M "$FILTER" '*' ref \
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT2 -b "$BASEDN" -M "$FILTER" '*' ref \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -299,7 +240,7 @@ echo "	base=\"$BASEDN\"..."
 echo "# searching filter=\"$FILTER\"" >> $SEARCHOUT
 echo "# 	attrs=\"seeAlso\"" >> $SEARCHOUT
 echo "# 	base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" seeAlso \
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT2 -b "$BASEDN" "$FILTER" seeAlso \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -315,7 +256,7 @@ echo "	base=\"$BASEDN\"..."
 echo "# searching filter=\"$FILTER\"" >> $SEARCHOUT
 echo "# 	attrs=\"uid\"" >> $SEARCHOUT
 echo "# 	base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" uid \
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT2 -b "$BASEDN" "$FILTER" uid \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -331,7 +272,7 @@ echo "	base=\"$BASEDN\"..."
 echo "# searching filter=\"$FILTER\"" >> $SEARCHOUT
 echo "# 	attrs=\"member\"" >> $SEARCHOUT
 echo "# 	base=\"$BASEDN\"..." >> $SEARCHOUT
-$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" member \
+$LDAPSEARCH -S "" -h $LOCALHOST -p $PORT2 -b "$BASEDN" "$FILTER" member \
 	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -343,20 +284,20 @@ fi
 echo "Filtering ldapsearch results..."
 . $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
 echo "Filtering original ldif used to create database..."
-. $LDIFFILTER < $RELAYOUT > $LDIFFLT
+. $LDIFFILTER < $METAOUT > $LDIFFLT
 echo "Comparing filter output..."
 $CMP $SEARCHFLT $LDIFFLT > $CMPOUT
 	
 if test $? != 0 ; then
-	echo "comparison failed - relay search/modification didn't succeed"
+	echo "comparison failed - meta search/modification didn't succeed"
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
 
 BASEDN="o=Example,c=US"
 echo "Changing password to database \"$BASEDN\"..."
-$LDAPPASSWD -h $LOCALHOST -p $PORT1 -D "cn=Manager,$BASEDN" -w $PASSWD \
-	-s $PASSWD "cn=Added User,ou=Alumni Association,ou=People,$BASEDN" \
+$LDAPPASSWD -h $LOCALHOST -p $PORT2 -D "cn=Manager,$BASEDN" -w $PASSWD \
+	-s $PASSWD "cn=Ursula Hampster,ou=Alumni Association,ou=People,$BASEDN" \
 	>> $TESTOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -365,10 +306,9 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-BASEDN="o=Beispiel,c=DE"
 echo "Binding with newly changed password to database \"$BASEDN\"..."
-$LDAPWHOAMI -h $LOCALHOST -p $PORT1 \
-	-D "cn=Added User,ou=Alumni Association,ou=People,$BASEDN" \
+$LDAPWHOAMI -h $LOCALHOST -p $PORT2 \
+	-D "cn=Ursula Hampster,ou=Alumni Association,ou=People,$BASEDN" \
 	-w $PASSWD >> $TESTOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
@@ -377,11 +317,43 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
-BASEDN="o=Esempio,c=IT"
+echo "Binding as newly added user to database \"$BASEDN\"..."
+$LDAPWHOAMI -h $LOCALHOST -p $PORT2 \
+	-D "cn=Added User,ou=Same as above,ou=Meta,$BASEDN" \
+	-w $PASSWD >> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "WhoAmI failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Changing password to database \"$BASEDN\"..."
+$LDAPPASSWD -h $LOCALHOST -p $PORT2 -D "cn=Manager,$BASEDN" -w $PASSWD \
+	-s meta "cn=Added User,ou=Same as above,ou=Meta,$BASEDN" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "Passwd ExOp failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Binding with newly changed password to database \"$BASEDN\"..."
+$LDAPWHOAMI -h $LOCALHOST -p $PORT2 \
+	-D "cn=Added User,ou=Same as above,ou=Meta,$BASEDN" \
+	-w meta >> $TESTOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "WhoAmI failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
 echo "Comparing to database \"$BASEDN\"..."
-$LDAPCOMPARE -h $LOCALHOST -p $PORT1 \
-	"cn=Added User,ou=Alumni Association,ou=People,$BASEDN" \
-	"seeAlso:cn=All Staff,ou=Groups,$BASEDN" >> $TESTOUT 2>&1
+$LDAPCOMPARE -h $LOCALHOST -p $PORT2 \
+	"cn=Another Added Group,ou=Groups,$BASEDN" \
+	"member:cn=Added Group,ou=Groups,$BASEDN" >> $TESTOUT 2>&1
 RC=$?
 if test $RC != 6 ; then
 	echo "Compare failed ($RC)!"
@@ -390,4 +362,7 @@ if test $RC != 6 ; then
 fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
+
+echo ">>>>> Test succeeded"
+exit 0
 
