silence warnings; misc cleanup; test refresh as non-allowed user

diff --git a/tests/scripts/test046-dds b/tests/scripts/test046-dds
--- a/tests/scripts/test046-dds
+++ b/tests/scripts/test046-dds
@@ -396,7 +396,7 @@ member: $BJORNSDN
 dn: $MEETINGDN
 changetype: modify
 add: member
-member: $JAJDN
+member: $JOHNDDN
 EOMODS
 RC=$?
 if test $RC != 0 ; then
@@ -469,6 +469,17 @@ fi
 
 echo "Trying to refresh the meeting anonymously (should fail)..."
 $LDAPEXOP -h $LOCALHOST -p $PORT1 \
+	"refresh" "$MEETINGDN" "240" \
+	>> $TESTOUT 2>&1
+RC=$?
+if test $RC = 0 ; then
+	echo "ldapexop should have failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+echo "Trying to refresh the meeting as $JAJDN (should fail)..."
+$LDAPEXOP -D "$JAJDN" -w "jaj" -h $LOCALHOST -p $PORT1 \
 	"refresh" "$MEETINGDN" "240" \
 	>> $TESTOUT 2>&1
 RC=$?
