Sync with HEAD

diff --git a/tests/scripts/test042-valsort b/tests/scripts/test042-valsort
--- a/tests/scripts/test042-valsort
+++ b/tests/scripts/test042-valsort
@@ -23,6 +23,14 @@ fi
 
 mkdir -p $TESTDIR $DBDIR1
 
+$SLAPPASSWD -g -n > $CONFIGPWF
+RC=$?
+if test $RC != 0 ; then
+	echo "slappasswd failed ($RC)!"
+	exit $RC
+fi
+read CONFIGPW < $CONFIGPWF
+
 echo "Running slapadd to build slapd database..."
 . $CONFFILTER $BACKEND $MONITORDB < $VALSORTCONF > $CONF1
 $SLAPADD -f $CONF1 -l $LDIFVALSORT
@@ -85,11 +93,9 @@ if test $? != 0 ; then
 	exit 1
 fi
 
-echo ">>>>> Test succeeded"
-
 echo "Reconfiguring slapd to test valsort descending"
 
-$LDAPMODIFY -x -D cn=config -h $LOCALHOST -p $PORT1 -w $PASSWD > \
+$LDAPMODIFY -x -D cn=config -h $LOCALHOST -p $PORT1 -y $CONFIGPWF > \
 	$TESTOUT 2>&1 << EOMODS
 version: 1
 dn: olcOverlay={0}valsort,olcDatabase={1}$BACKEND,cn=config
@@ -132,8 +138,6 @@ if test $? != 0 ; then
 	test $KILLSERVERS != no && kill -HUP $KILLPIDS
 	exit 1
 fi
-
-echo ">>>>> Test succeeded"
 
 echo "Adding a valsort record with weighted ou..."
 
@@ -217,8 +221,8 @@ fi
 
 test $KILLSERVERS != no && kill -HUP $KILLPIDS
 
-echo ">>>>> Test succeeded"
-
 test $KILLSERVERS != no && wait
+
+echo ">>>>> Test succeeded"
 
 exit 0
