slightly rework user/operational attributes handling (including fixing a bug in the logic of the previous change to backend_operational()); cleanup; more improvements to slapo-rwm and back-relay

diff --git a/tests/scripts/test030-relay b/tests/scripts/test030-relay
--- a/tests/scripts/test030-relay
+++ b/tests/scripts/test030-relay
@@ -114,7 +114,7 @@ fi
 BASEDN="o=Beispiel,c=DE"
 echo "modifying database \"$BASEDN\"..."
 $LDAPMODIFY -v -D "cn=Manager,$BASEDN" -h $LOCALHOST -p $PORT1 -w $PASSWD \
-	>> $TESTOUT 2>&1 << EOMODS
+	-e manageDSAit >> $TESTOUT 2>&1 << EOMODS
 dn: cn=Added User,ou=Alumni Association,ou=People,$BASEDN
 changetype: add
 objectClass: OpenLDAPperson
@@ -125,7 +125,8 @@ seealso: cn=All Staff,ou=Groups,$BASEDN
 homephone: +49 1234567890
 drink: Beer
 mail: auser@mail.alumni.example.com
-telephonenumber: +1 313 555 4178
+telephonenumber: +49 1234-567-890
+description: Just added in o=Beispiel,c=DE naming context
 
 dn: cn=Ursula Hampster,ou=Alumni Association,ou=People,$BASEDN
 changetype: modify
@@ -133,7 +134,7 @@ add: seeAlso
 seeAlso: cn=Ursula Hampster,ou=Alumni Association,ou=People,$BASEDN
 -
 add: description
-description: Just added self in $BASEDN virtual naming context
+description: Just added self to seeAlso in $BASEDN virtual naming context
 -
 
 dn: cn=Mark Elliot,ou=Alumni Association,ou=People,$BASEDN
@@ -150,6 +151,22 @@ newrdn: cn=Jane Q. Doe
 deleteoldrdn: 1
 newsuperior: ou=Information Technology Division,ou=People,$BASEDN
 
+dn: ou=Referrals,$BASEDN
+changetype: add
+objectclass: referral
+objectclass: extensibleObject
+ou: Referrals
+ref: ${URI1}ou=Referrals,$BASEDN
+description: Just added as ${URI1}ou=Referrals,$BASEDN
+
+dn: ou=Referrals,$BASEDN
+changetype: modify
+replace: ref
+ref: ${URI2}ou=Referrals,$BASEDN
+-
+add: description
+description: ...and modified as ${URI2}ou=Referrals,$BASEDN
+-
 EOMODS
 
 if test $RC != 0 ; then
@@ -161,6 +178,57 @@ fi
 BASEDN="o=Esempio,c=IT"
 echo "searching base=\"$BASEDN\"..."
 $LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "Search failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+FILTER="(objectClass=referral)"
+echo "searching filter=\"$FILTER\""
+echo "	attrs=\"'*' ref\"..."
+
+BASEDN="dc=example,dc=com"
+echo "	base=\"$BASEDN\"..."
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" "*" ref \
+	-e manageDSAit >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "Search failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+BASEDN="o=Example,c=US"
+echo "	base=\"$BASEDN\"..."
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" "*" ref \
+	-e manageDSAit >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "Search failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+BASEDN="o=Esempio,c=IT"
+echo "	base=\"$BASEDN\"..."
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" "*" ref \
+	-e manageDSAit >> $SEARCHOUT 2>&1
+RC=$?
+if test $RC != 0 ; then
+	echo "Search failed ($RC)!"
+	test $KILLSERVERS != no && kill -HUP $KILLPIDS
+	exit $RC
+fi
+
+BASEDN="o=Example,c=US"
+FILTER="(seeAlso=cn=all staff,ou=Groups,$BASEDN)"
+echo "searching filter=\"$FILTER\""
+echo "	attrs=\"seeAlso\"..."
+echo "	base=\"$BASEDN\""
+$LDAPSEARCH -h $LOCALHOST -p $PORT1 -b "$BASEDN" "$FILTER" seeAlso \
+	>> $SEARCHOUT 2>&1
 RC=$?
 if test $RC != 0 ; then
 	echo "Search failed ($RC)!"
@@ -193,6 +261,7 @@ if test $RC != 0 ; then
 	exit $RC
 fi
 
+BASEDN="o=Beispiel,c=DE"
 echo "binding with newly changed password to database \"$BASEDN\"..."
 $LDAPWHOAMI -h $LOCALHOST -p $PORT1 \
 	-D "cn=Added User,ou=Alumni Association,ou=People,$BASEDN" \
